In [86]:
import pandas as pd
import numpy as np

In [87]:
semana_1 = pd.read_csv("../data/staging/operaciones_semana_2025-04-27_2025-05-03.csv")
semana_2 = pd.read_csv("../data/staging/operaciones_semana_2025-05-04_2025-05-10.csv")
semana_3 = pd.read_csv("../data/staging/operaciones_semana_2025-05-11_2025-05-17.csv")
semana_4 = pd.read_csv("../data/staging/operaciones_semana_2025-05-18_2025-05-24.csv")
semana_5 = pd.read_csv("../data/staging/operaciones_semana_2025-05-25_2025-05-31.csv")
semana_6 = pd.read_csv("../data/staging/operaciones_semana_2025-06-01_2025-06-06.csv")

In [88]:
df = pd.concat([semana_1, semana_2, semana_3, semana_4, semana_5, semana_6], ignore_index=True)
df.head(10).T

,0,1,2,3,4,5,6,7,8,9
fechaOperacion,2025-05-03T23:50:33.257,2025-05-03T11:31:36.837,2025-05-03T09:00:36.66,2025-05-03T08:59:09.52,2025-05-02T23:50:47.7,2025-05-02T23:50:40.5,2025-05-02T23:50:36.897,2025-05-02T23:50:33.343,2025-05-02T23:32:16.323,2025-05-02T23:32:12.277
fechaConcertacion,2025-05-03T00:00:00,2025-05-03T00:00:00,2025-04-30T00:00:00,2025-04-30T00:00:00,2025-05-02T00:00:00,2025-05-02T00:00:00,2025-05-02T00:00:00,2025-05-02T00:00:00,2025-05-02T00:00:00,2025-05-02T00:00:00
tipoOperacion,Contrato,Contrato,Contrato,Contrato,Contrato,Contrato,Contrato,Contrato,Contrato,Contrato
tipoModalidad,Compraventa,Compraventa,Compraventa,Compraventa,Compraventa,Compraventa,Compraventa,Compraventa,Compraventa,Compraventa
tipoOiv,Fijar Precio/Mercado Comprador,Precio Hecho,Precio Hecho,Precio Hecho,Fijar Precio/Mercado Comprador,Fijar Precio/Mercado Comprador,Fijar Precio/Mercado Comprador,Fijar Precio/Mercado Comprador,Fijar Precio/Otros,Fijar Precio/Otros
grano,MAIZ,TRIGO PAN,SOJA,SOJA,MAIZ,MAIZ,SOJA,MAIZ,SOJA,SOJA
volumenTN,1000.0,283.31,338.14,295.99,540.0,1000.0,1000.0,360.0,90.0,210.0
condicionCalidad,Cámara,Art. 12,Fábrica,Fábrica,Cámara,Cámara,Fábrica,Cámara,Cámara,Cámara
condicionCalidadAuxiliar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
procedenciaProvincia,CÓRDOBA,BUENOS AIRES,CÓRDOBA,CÓRDOBA,CÓRDOBA,CÓRDOBA,BUENOS AIRES,SANTA FE,SALTA,CÓRDOBA
procedenciaLocalidad,GUATIMOZIN,NAVARRO,MONTE BUEY,MONTE BUEY,MARCOS JUAREZ,GUATIMOZIN,PERGAMINO,CAFFERATA,ROSARIO DE LA FRONTE,RIO CUARTO
simboloPrecioPorTN,NaN,$,$,$,NaN,NaN,NaN,NaN,NaN,NaN
precioTN,NaN,229440.0,297483.1,297483.1,NaN,NaN,NaN,NaN,NaN,NaN
lugarEntrega,Rosario N/En destino,Zona 5/En destino,Zona 8/En destino,Zona 8/En destino,Rosario N/En destino,Rosario N/En destino,Zona 6/En destino,Rosario N/En destino,Rosario N/En destino,Rosario N/En destino
fechaEntregaDesde,2025-05-03T00:00:00,2025-05-03T00:00:00,2025-04-30T00:00:00,2025-04-30T00:00:00,2025-05-02T00:00:00,2025-05-02T00:00:00,2025-05-02T00:00:00,2025-05-03T00:00:00,2025-05-02T00:00:00,2025-05-02T00:00:00
fechaEntregaHasta,2025-05-07T00:00:00,2025-05-03T00:00:00,2025-04-30T00:00:00,2025-04-30T00:00:00,2025-05-07T00:00:00,2025-05-07T00:00:00,2025-05-20T00:00:00,2025-05-07T00:00:00,2025-06-01T00:00:00,2025-06-01T00:00:00
condicionPago,A plazo,A plazo,A plazo,A plazo,A plazo,A plazo,A plazo,A plazo,A plazo,A plazo
esDestinoFinal,SI,SI,SI,SI,SI,SI,SI,SI,SI,SI
cosecha,COSECHA 24/25,COSECHA 24/25,COSECHA 24/25,COSECHA 24/25,COSECHA 24/25,COSECHA 24/25,COSECHA 24/25,COSECHA 24/25,COSECHA 24/25,COSECHA 24/25
numeroOperacionInstancia,1,1,1,1,1,1,1,1,1,1
nroOperacion,1935460251,1935140257,1935100255,1935080254,1935060253,1935040252,1935030257,1935020251,1935000250,1934990257
esUltimaInstancia,Si,Si,Si,Si,Si,Si,Si,Si,Si,Si

In [89]:
df.isna().sum()

fechaOperacion                  0
fechaConcertacion               0
tipoOperacion                   0
tipoModalidad                   0
tipoOiv                         0
grano                           0
volumenTN                       3
condicionCalidad                0
condicionCalidadAuxiliar    10866
procedenciaProvincia            0
procedenciaLocalidad            0
simboloPrecioPorTN           2295
precioTN                     2171
lugarEntrega                    0
fechaEntregaDesde               0
fechaEntregaHasta               0
condicionPago                   0
esDestinoFinal                  0
cosecha                        24
numeroOperacionInstancia        0
nroOperacion                    0
esUltimaInstancia               0
dtype: int64

In [90]:
df['tipoOiv'].value_counts() # Agrupar en una sola precio a fijar

tipoOiv
Precio Hecho                      5142
Fijar Precio/Mercado Comprador    2276
Fijar Precio/Otros                2239
Fijar Precio/Prec. Cam.           1132
Fijar Precio/M. T. País            218
Fijar Precio/Fas teórico             2
Fijar Precio/PR R. Conj.             1
Name: count, dtype: int64

In [91]:
df['lugarEntrega'].value_counts()

lugarEntrega
Rosario N/En destino    2354
Rosario S/En destino     953
Zona 13/En destino       681
Zona 9/En destino        663
Zona 8/En destino        632
Zona 6/En destino        594
Zona 14/En destino       478
Zona 11/En destino       454
Zona 18/En destino       368
Zona 5/En destino        359
Cordoba/En destino       313
Zona 7/En destino        266
Zona 15/En destino       251
Zona 12/En destino       235
Zona 15/En origen        207
Cordoba/En origen        168
Zona 16/En origen        166
Quequen/En destino       163
Bs As/En destino         152
B.Blanca/En destino      151
Zona 11/En origen        142
Zona 25/En destino       135
Zona 16/En destino       118
Zona 2/En destino        109
Zona 3/En destino        108
Zona 17/En origen        108
Zona 7/En origen          94
Zona 4/En destino         76
Rosario N/En origen       62
Zona 14/En origen         57
Zona 6/En origen          56
Zona 10/En destino        54
Zona 17/En destino        52
Zona 8/En origen          45
Zona 18/En origen         43
Zona 13/En origen         27
Zona 9/En origen          26
Zona 25/En origen         25
Zona 5/En origen          16
Bs As/En origen           13
Quequen/En origen          9
Zona 12/En origen          8
Zona 4/En origen           8
Zona 10/En origen          7
Zona 26/En origen          2
Zona 2/En origen           1
Zona 1/En destino          1
Name: count, dtype: int64

In [92]:
precio_a_fijar = ['Fijar Precio/Mercado Comprador', 'Fijar Precio/Otros', 'Fijar Precio/Prec. Cam.', 'Fijar Precio/M. T. País', 'Fijar Precio/Fas teórico', 'Fijar Precio/PR R. Conj.']

# renombrar valores de tipoOiv a precio a fijar y otros
df['tipoOiv_v2'] = df['tipoOiv'].replace(precio_a_fijar, 'Precio a Fijar')
df['tipoOiv_v2'].value_counts()

tipoOiv_v2
Precio a Fijar    5868
Precio Hecho      5142
Name: count, dtype: int64

In [93]:
df[df['volumenTN'].isna()].T

,4291,6672,8968
fechaOperacion,2025-05-15T15:07:32.14,2025-05-22T09:12:03.37,2025-05-29T14:02:17.427
fechaConcertacion,2025-05-15T00:00:00,2025-05-22T00:00:00,2025-05-29T00:00:00
tipoOperacion,Contrato,Contrato,Contrato
tipoModalidad,Compraventa,Compraventa,Compraventa
tipoOiv,Fijar Precio/Otros,Fijar Precio/Otros,Fijar Precio/Otros
grano,MAIZ,MAIZ,MAIZ
volumenTN,NaN,NaN,NaN
condicionCalidad,Cámara,Cámara,Cámara
condicionCalidadAuxiliar,NaN,NaN,NaN
procedenciaProvincia,CÓRDOBA,CÓRDOBA,CÓRDOBA
procedenciaLocalidad,ALEJANDRO ROCA,ALEJANDRO ROCA,ALEJANDRO ROCA
simboloPrecioPorTN,NaN,NaN,NaN
precioTN,NaN,NaN,NaN
lugarEntrega,Zona 9/En destino,Zona 9/En destino,Zona 9/En destino
fechaEntregaDesde,2025-05-15T00:00:00,2025-05-22T00:00:00,2025-05-29T00:00:00
fechaEntregaHasta,2025-05-31T00:00:00,2025-05-31T00:00:00,2025-05-31T00:00:00
condicionPago,A plazo,A plazo,A plazo
esDestinoFinal,SI,SI,SI
cosecha,COSECHA 24/25,COSECHA 24/25,COSECHA 24/25
numeroOperacionInstancia,1,1,1
nroOperacion,2236510258,2409260252,2592870250
esUltimaInstancia,Si,Si,Si
tipoOiv_v2,Precio a Fijar,Precio a Fijar,Precio a Fijar

In [94]:
# Grano por localidad

df_prov_loc = df.groupby(['procedenciaProvincia', 'procedenciaLocalidad', 'grano']).agg({'volumenTN': ['sum', 'mean', 'count']})
df_prov_loc.head(10)

                                                       volumenTN               \
                                                             sum         mean
procedenciaProvincia procedenciaLocalidad grano
BUENOS AIRES         16 DE JULIO          TRIGO CAND.      47.66    47.660000
                     25 DE MAYO           CEBADA CERV.   1200.00   600.000000
                                          MAIZ           3577.40   255.528571
                                          SOJA           2407.90   185.223077
                                          TRIGO PAN        60.00    60.000000
                     30 DE AGOSTO         SOJA           1100.00   550.000000
                     9 DE ABRIL           MAIZ           2000.00  2000.000000
                     9 DE JULIO           MAIZ           5270.00   585.555556
                                          SOJA           9360.08   780.006667
                                          TRIGO PAN      3410.00   162.380952


                                                       count
procedenciaProvincia procedenciaLocalidad grano
BUENOS AIRES         16 DE JULIO          TRIGO CAND.      1
                     25 DE MAYO           CEBADA CERV.     2
                                          MAIZ            14
                                          SOJA            13
                                          TRIGO PAN        1
                     30 DE AGOSTO         SOJA             2
                     9 DE ABRIL           MAIZ             1
                     9 DE JULIO           MAIZ             9
                                          SOJA            12
                                          TRIGO PAN       21

In [95]:

# Agrupacion por grano
df.groupby('grano').agg({'volumenTN': ['sum', 'mean', 'count']})

               volumenTN
                     sum        mean count
grano
ACEITE SOJA      4917.10   50.691753    97
ARROZ C.L.A      1472.97  368.242500     4
ARROZ C.L.F     31050.06  188.182182   165
CEBADA CERV.    78230.08  597.176183   131
CEBADA FORR.    10403.93  297.255143    35
GIRASOL         34305.78  131.945308   260
MAIZ           985656.61  446.807167  2206
SOJA          1238394.38  187.465089  6606
SORGO            1555.76   64.823333    24
TRIGO CAND.     14213.95  418.057353    34
TRIGO PAN      248237.23  171.790471  1445

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11010 entries, 0 to 11009
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   fechaOperacion            11010 non-null  object
 1   fechaConcertacion         11010 non-null  object
 2   tipoOperacion             11010 non-null  object
 3   tipoModalidad             11010 non-null  object
 4   tipoOiv                   11010 non-null  object
 5   grano                     11010 non-null  object
 6   volumenTN                 11007 non-null  float64
 7   condicionCalidad          11010 non-null  object
 8   condicionCalidadAuxiliar  144 non-null    object
 9   procedenciaProvincia      11010 non-null  object
 10  procedenciaLocalidad      11010 non-null  object
 11  simboloPrecioPorTN        8715 non-null   object
 12  precioTN                  8839 non-null   float64
 13  lugarEntrega              11010 non-null  object
 14  fechaEntregaDesde         11010 non-null  object
 15  fechaEntregaHasta         11010 non-null  object
 16  condicionPago             11010 non-null  object
 17  esDestinoFinal            11010 non-null  object
 18  cosecha                   10986 non-null  object
 19  numeroOperacionInstancia  11010 non-null  int64
 20  nroOperacion              11010 non-null  int64
 21  esUltimaInstancia         11010 non-null  object
 22  tipoOiv_v2                11010 non-null  object
dtypes: float64(2), int64(2), object(19)
memory usage: 1.9+ MB

In [97]:
for col in df.select_dtypes(include=['object']).columns:
    print(df[col].value_counts(dropna=False).head(10))

fechaOperacion
2025-05-08T15:53:22.677    3
2025-04-30T09:39:55.34     2
2025-05-05T10:32:15.427    2
2025-05-21T15:42:41.747    2
2025-05-05T11:49:16.9      2
2025-05-15T15:00:52.237    2
2025-05-19T17:43:52.297    2
2025-05-27T10:30:20.897    2
2025-04-30T09:41:37.437    2
2025-05-27T16:11:40.843    2
Name: count, dtype: int64
fechaConcertacion
2025-05-12T00:00:00    402
2025-05-14T00:00:00    381
2025-05-06T00:00:00    367
2025-05-05T00:00:00    358
2025-04-30T00:00:00    358
2025-05-20T00:00:00    349
2025-04-28T00:00:00    349
2025-05-30T00:00:00    346
2025-05-08T00:00:00    338
2025-05-19T00:00:00    333
Name: count, dtype: int64
tipoOperacion
Contrato                    7095
Fijación                    3518
Rectificación                233
Anulación                    103
Anulación Fijación            45
Rectificación Fijación        10
Rectificación Ampliación       6
Name: count, dtype: int64
tipoModalidad
Compraventa    9618
Canje          1392
Name: count, dtype: int64
tipoOiv
Precio Hecho                      5142
Fijar Precio/Mercado Comprador    2276
Fijar Precio/Otros                2239
Fijar Precio/Prec. Cam.           1132
Fijar Precio/M. T. País            218
Fijar Precio/Fas teórico             2
Fijar Precio/PR R. Conj.             1
Name: count, dtype: int64
grano
SOJA            6606
MAIZ            2209
TRIGO PAN       1445
GIRASOL          260
ARROZ C.L.F      165
CEBADA CERV.     131
ACEITE SOJA       97
CEBADA FORR.      35
TRIGO CAND.       34
SORGO             24
Name: count, dtype: int64
condicionCalidad
Cámara                    6342
Fábrica                   3535
Art. 12                    440
Otra                       432
Cámara con Condiciones     144
Crudo                       97
Proteína 10.5%              20
Name: count, dtype: int64
condicionCalidadAuxiliar
NaN                                      10866
OTRA                                        34
GLUTEN MINIMO 32                            25
NO BONIF. GR1, REB. GR3                     23
BONIFICACION POR MAS DE 25 DE GLUTEN        14
BONIFICACION POR MAS DE 25% DE GLUTEN        7
20 GL MINIMO                                 5
24 GL 78 PH                                  4
24  GLUTEN MINIMO                            4
PH 78, PR10                                  3
Name: count, dtype: int64
procedenciaProvincia
CÓRDOBA                3507
BUENOS AIRES           2450
SANTA FE               2272
ENTRE RÍOS             1236
SANTIAGO DEL ESTERO     547
LA PAMPA                249
TUCUMÁN                 219
SALTA                   206
CHACO                   167
SAN LUIS                 98
Name: count, dtype: int64
procedenciaLocalidad
ALVEAR             183
BRAGADO            156
SAN JORGE          138
VICUÑA MACKENNA    126
RIO CUARTO         126
BANDERA            120
AZUL               115
ALBERTI            103
SALTO              100
LUIS PALACIOS       84
Name: count, dtype: int64
simboloPrecioPorTN
$      7361
NaN    2295
U$S    1354
Name: count, dtype: int64
lugarEntrega
Rosario N/En destino    2354
Rosario S/En destino     953
Zona 13/En destino       681
Zona 9/En destino        663
Zona 8/En destino        632
Zona 6/En destino        594
Zona 14/En destino       478
Zona 11/En destino       454
Zona 18/En destino       368
Zona 5/En destino        359
Name: count, dtype: int64
fechaEntregaDesde
2025-04-01T00:00:00    500
2025-05-14T00:00:00    371
2025-05-12T00:00:00    360
2025-05-05T00:00:00    358
2025-05-06T00:00:00    350
2025-04-30T00:00:00    349
2025-04-28T00:00:00    331
2025-05-20T00:00:00    330
2025-05-08T00:00:00    329
2025-05-19T00:00:00    328
Name: count, dtype: int64
fechaEntregaHasta
2025-05-31T00:00:00    790
2025-04-30T00:00:00    685
2025-05-30T00:00:00    441
2025-05-28T00:00:00    368
2025-05-15T00:00:00    317
2025-06-30T00:00:00    271
2025-06-12T00:00:00    252
2025-05-29T00:00:00    226
2025-05-22T00:00:00    208
2025-05-16T00:00:00    193
Name: count, dtype: int64
condicionPago
A plazo    11010
Name: count, dtype: int64
esDestinoFinal
SI    8102
NO    2908
Name: count, dtype: int64
cosecha
COSECHA 24/25    8720
COSECHA 23/24    1427
COSECHA 2021      187
COSECHA 20/21     142
COSECHA 22/23     121
COSECHA 2025       87
COSECHA 25/26      80
COSECHA 21/22      73
COSECHA 2024       47
COSECHA 2020       25
Name: count, dtype: int64
esUltimaInstancia
Si    10762
No      248
Name: count, dtype: int64
tipoOiv_v2
Precio a Fijar    5868
Precio Hecho      5142
Name: count, dtype: int64

In [98]:
df['nroOperacion'].nunique()

8626

In [99]:
df.shape[0]

11010

In [100]:
df.columns

Index(['fechaOperacion', 'fechaConcertacion', 'tipoOperacion', 'tipoModalidad',
       'tipoOiv', 'grano', 'volumenTN', 'condicionCalidad',
       'condicionCalidadAuxiliar', 'procedenciaProvincia',
       'procedenciaLocalidad', 'simboloPrecioPorTN', 'precioTN',
       'lugarEntrega', 'fechaEntregaDesde', 'fechaEntregaHasta',
       'condicionPago', 'esDestinoFinal', 'cosecha',
       'numeroOperacionInstancia', 'nroOperacion', 'esUltimaInstancia',
       'tipoOiv_v2'],
      dtype='object')

In [101]:
operaciones_duplicadas = df[df['nroOperacion'].duplicated(keep=False)].sort_values(by='nroOperacion')
operaciones_duplicadas

,fechaOperacion,fechaConcertacion,tipoOperacion,tipoModalidad,tipoOiv,grano,volumenTN,condicionCalidad,condicionCalidadAuxiliar,procedenciaProvincia,...,lugarEntrega,fechaEntregaDesde,fechaEntregaHasta,condicionPago,esDestinoFinal,cosecha,numeroOperacionInstancia,nroOperacion,esUltimaInstancia,tipoOiv_v2
261,2025-04-30T22:30:28.127,2025-01-02T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,1600.00,Fábrica,NaN,SANTA FE,...,Rosario N/En destino,2025-03-15T00:00:00,2025-04-15T00:00:00,A plazo,SI,COSECHA 24/25,19,32220258,Si,Precio a Fijar
676,2025-04-29T22:30:27.4,2025-01-02T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,1000.00,Fábrica,NaN,SANTA FE,...,Rosario N/En destino,2025-03-15T00:00:00,2025-04-15T00:00:00,A plazo,SI,COSECHA 24/25,18,32220258,Si,Precio a Fijar
1073,2025-04-28T22:30:16.94,2025-01-02T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,500.00,Fábrica,NaN,SANTA FE,...,Rosario N/En destino,2025-03-15T00:00:00,2025-04-15T00:00:00,A plazo,SI,COSECHA 24/25,17,32220258,Si,Precio a Fijar
4900,2025-05-14T08:42:24.49,2025-01-03T00:00:00,Anulación Fijación,Compraventa,Fijar Precio/Otros,SOJA,90.00,Cámara,NaN,SANTIAGO DEL ESTERO,...,Zona 15/En destino,2025-05-01T00:00:00,2025-05-31T00:00:00,A plazo,SI,COSECHA 24/25,3,43740253,No,Precio a Fijar
4885,2025-05-14T08:44:09.9,2025-01-03T00:00:00,Fijación,Compraventa,Fijar Precio/Otros,SOJA,75.00,Cámara,NaN,SANTIAGO DEL ESTERO,...,Zona 15/En destino,2025-05-01T00:00:00,2025-05-31T00:00:00,A plazo,SI,COSECHA 24/25,4,43740253,Si,Precio a Fijar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2973,2025-05-06T15:51:23.807,2024-12-30T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,TRIGO PAN,32.12,Art. 12,NaN,BUENOS AIRES,...,Zona 2/En destino,2025-01-01T00:00:00,2025-06-30T00:00:00,A plazo,SI,COSECHA 24/25,5,6136190243,Si,Precio a Fijar
4050,2025-05-16T10:08:46.7,2023-11-23T00:00:00,Fijación,Compraventa,Fijar Precio/Otros,TRIGO PAN,50.00,Otra,NaN,CÓRDOBA,...,Cordoba/En destino,2023-11-23T00:00:00,2023-11-23T00:00:00,A plazo,SI,COSECHA 23/24,8,6452070233,Si,Precio a Fijar
2246,2025-05-08T10:05:40.03,2023-11-23T00:00:00,Fijación,Compraventa,Fijar Precio/Otros,TRIGO PAN,50.00,Otra,NaN,CÓRDOBA,...,Cordoba/En destino,2023-11-23T00:00:00,2023-11-23T00:00:00,A plazo,SI,COSECHA 23/24,7,6452070233,Si,Precio a Fijar
8760,2025-05-29T22:30:42.523,2023-12-06T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,600.00,Otra,NaN,BUENOS AIRES,...,Rosario N/En destino,2023-12-06T00:00:00,2024-01-06T00:00:00,A plazo,SI,COSECHA 22/23,2,6641750237,Si,Precio a Fijar
8103,2025-05-30T22:35:02.823,2023-12-06T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,900.00,Otra,NaN,BUENOS AIRES,...,Rosario N/En destino,2023-12-06T00:00:00,2024-01-06T00:00:00,A plazo,SI,COSECHA 22/23,3,6641750237,Si,Precio a Fijar

In [102]:
operaciones_duplicadas

,fechaOperacion,fechaConcertacion,tipoOperacion,tipoModalidad,tipoOiv,grano,volumenTN,condicionCalidad,condicionCalidadAuxiliar,procedenciaProvincia,...,lugarEntrega,fechaEntregaDesde,fechaEntregaHasta,condicionPago,esDestinoFinal,cosecha,numeroOperacionInstancia,nroOperacion,esUltimaInstancia,tipoOiv_v2
261,2025-04-30T22:30:28.127,2025-01-02T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,1600.00,Fábrica,NaN,SANTA FE,...,Rosario N/En destino,2025-03-15T00:00:00,2025-04-15T00:00:00,A plazo,SI,COSECHA 24/25,19,32220258,Si,Precio a Fijar
676,2025-04-29T22:30:27.4,2025-01-02T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,1000.00,Fábrica,NaN,SANTA FE,...,Rosario N/En destino,2025-03-15T00:00:00,2025-04-15T00:00:00,A plazo,SI,COSECHA 24/25,18,32220258,Si,Precio a Fijar
1073,2025-04-28T22:30:16.94,2025-01-02T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,500.00,Fábrica,NaN,SANTA FE,...,Rosario N/En destino,2025-03-15T00:00:00,2025-04-15T00:00:00,A plazo,SI,COSECHA 24/25,17,32220258,Si,Precio a Fijar
4900,2025-05-14T08:42:24.49,2025-01-03T00:00:00,Anulación Fijación,Compraventa,Fijar Precio/Otros,SOJA,90.00,Cámara,NaN,SANTIAGO DEL ESTERO,...,Zona 15/En destino,2025-05-01T00:00:00,2025-05-31T00:00:00,A plazo,SI,COSECHA 24/25,3,43740253,No,Precio a Fijar
4885,2025-05-14T08:44:09.9,2025-01-03T00:00:00,Fijación,Compraventa,Fijar Precio/Otros,SOJA,75.00,Cámara,NaN,SANTIAGO DEL ESTERO,...,Zona 15/En destino,2025-05-01T00:00:00,2025-05-31T00:00:00,A plazo,SI,COSECHA 24/25,4,43740253,Si,Precio a Fijar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2973,2025-05-06T15:51:23.807,2024-12-30T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,TRIGO PAN,32.12,Art. 12,NaN,BUENOS AIRES,...,Zona 2/En destino,2025-01-01T00:00:00,2025-06-30T00:00:00,A plazo,SI,COSECHA 24/25,5,6136190243,Si,Precio a Fijar
4050,2025-05-16T10:08:46.7,2023-11-23T00:00:00,Fijación,Compraventa,Fijar Precio/Otros,TRIGO PAN,50.00,Otra,NaN,CÓRDOBA,...,Cordoba/En destino,2023-11-23T00:00:00,2023-11-23T00:00:00,A plazo,SI,COSECHA 23/24,8,6452070233,Si,Precio a Fijar
2246,2025-05-08T10:05:40.03,2023-11-23T00:00:00,Fijación,Compraventa,Fijar Precio/Otros,TRIGO PAN,50.00,Otra,NaN,CÓRDOBA,...,Cordoba/En destino,2023-11-23T00:00:00,2023-11-23T00:00:00,A plazo,SI,COSECHA 23/24,7,6452070233,Si,Precio a Fijar
8760,2025-05-29T22:30:42.523,2023-12-06T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,600.00,Otra,NaN,BUENOS AIRES,...,Rosario N/En destino,2023-12-06T00:00:00,2024-01-06T00:00:00,A plazo,SI,COSECHA 22/23,2,6641750237,Si,Precio a Fijar
8103,2025-05-30T22:35:02.823,2023-12-06T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,900.00,Otra,NaN,BUENOS AIRES,...,Rosario N/En destino,2023-12-06T00:00:00,2024-01-06T00:00:00,A plazo,SI,COSECHA 22/23,3,6641750237,Si,Precio a Fijar

In [103]:
operaciones_duplicadas['operacion_id'] = (
    operaciones_duplicadas['nroOperacion'].astype(str)
    + '_'
    + operaciones_duplicadas['numeroOperacionInstancia'].astype(str)
)
operaciones_duplicadas['operacion_id']

261      32220258_19
676      32220258_18
1073     32220258_17
4900      43740253_3
4885      43740253_4
            ...
2973    6136190243_5
4050    6452070233_8
2246    6452070233_7
8760    6641750237_2
8103    6641750237_3
Name: operacion_id, Length: 3893, dtype: object

In [104]:
operaciones_duplicadas['operacion_id'].nunique()

3893

In [105]:
operaciones_duplicadas[['nroOperacion', 'fechaOperacion', 'fechaConcertacion', 'tipoOperacion', 'tipoModalidad',
       'tipoOiv', 'grano', 'volumenTN', 'condicionCalidad', 'procedenciaLocalidad', 'simboloPrecioPorTN', 'precioTN', 
       'lugarEntrega', 'fechaEntregaDesde', 'fechaEntregaHasta',
       'condicionPago', 'esDestinoFinal', 'cosecha',
       'numeroOperacionInstancia', 'nroOperacion', 'esUltimaInstancia', 'tipoOiv_v2']]

,nroOperacion,fechaOperacion,fechaConcertacion,tipoOperacion,tipoModalidad,tipoOiv,grano,volumenTN,condicionCalidad,procedenciaLocalidad,...,lugarEntrega,fechaEntregaDesde,fechaEntregaHasta,condicionPago,esDestinoFinal,cosecha,numeroOperacionInstancia,nroOperacion,esUltimaInstancia,tipoOiv_v2
261,32220258,2025-04-30T22:30:28.127,2025-01-02T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,1600.00,Fábrica,RAFAELA,...,Rosario N/En destino,2025-03-15T00:00:00,2025-04-15T00:00:00,A plazo,SI,COSECHA 24/25,19,32220258,Si,Precio a Fijar
676,32220258,2025-04-29T22:30:27.4,2025-01-02T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,1000.00,Fábrica,RAFAELA,...,Rosario N/En destino,2025-03-15T00:00:00,2025-04-15T00:00:00,A plazo,SI,COSECHA 24/25,18,32220258,Si,Precio a Fijar
1073,32220258,2025-04-28T22:30:16.94,2025-01-02T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,500.00,Fábrica,RAFAELA,...,Rosario N/En destino,2025-03-15T00:00:00,2025-04-15T00:00:00,A plazo,SI,COSECHA 24/25,17,32220258,Si,Precio a Fijar
4900,43740253,2025-05-14T08:42:24.49,2025-01-03T00:00:00,Anulación Fijación,Compraventa,Fijar Precio/Otros,SOJA,90.00,Cámara,LOS JURIES,...,Zona 15/En destino,2025-05-01T00:00:00,2025-05-31T00:00:00,A plazo,SI,COSECHA 24/25,3,43740253,No,Precio a Fijar
4885,43740253,2025-05-14T08:44:09.9,2025-01-03T00:00:00,Fijación,Compraventa,Fijar Precio/Otros,SOJA,75.00,Cámara,LOS JURIES,...,Zona 15/En destino,2025-05-01T00:00:00,2025-05-31T00:00:00,A plazo,SI,COSECHA 24/25,4,43740253,Si,Precio a Fijar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2973,6136190243,2025-05-06T15:51:23.807,2024-12-30T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,TRIGO PAN,32.12,Art. 12,RIVERA,...,Zona 2/En destino,2025-01-01T00:00:00,2025-06-30T00:00:00,A plazo,SI,COSECHA 24/25,5,6136190243,Si,Precio a Fijar
4050,6452070233,2025-05-16T10:08:46.7,2023-11-23T00:00:00,Fijación,Compraventa,Fijar Precio/Otros,TRIGO PAN,50.00,Otra,ONCATIVO,...,Cordoba/En destino,2023-11-23T00:00:00,2023-11-23T00:00:00,A plazo,SI,COSECHA 23/24,8,6452070233,Si,Precio a Fijar
2246,6452070233,2025-05-08T10:05:40.03,2023-11-23T00:00:00,Fijación,Compraventa,Fijar Precio/Otros,TRIGO PAN,50.00,Otra,ONCATIVO,...,Cordoba/En destino,2023-11-23T00:00:00,2023-11-23T00:00:00,A plazo,SI,COSECHA 23/24,7,6452070233,Si,Precio a Fijar
8760,6641750237,2025-05-29T22:30:42.523,2023-12-06T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,600.00,Otra,BRAGADO,...,Rosario N/En destino,2023-12-06T00:00:00,2024-01-06T00:00:00,A plazo,SI,COSECHA 22/23,2,6641750237,Si,Precio a Fijar
8103,6641750237,2025-05-30T22:35:02.823,2023-12-06T00:00:00,Fijación,Compraventa,Fijar Precio/Mercado Comprador,SOJA,900.00,Otra,BRAGADO,...,Rosario N/En destino,2023-12-06T00:00:00,2024-01-06T00:00:00,A plazo,SI,COSECHA 22/23,3,6641750237,Si,Precio a Fijar

In [106]:
df['operacion_id'] = (
    df['nroOperacion'].astype(str)
    + '_'
    + df['numeroOperacionInstancia'].astype(str)
)
df['operacion_id']

0        1935460251_1
1        1935140257_1
2        1935100255_1
3        1935080254_1
4        1935060253_1
             ...
11005    2661180253_1
11006    2661150257_1
11007    2661130256_1
11008    2661120250_1
11009    2661110255_1
Name: operacion_id, Length: 11010, dtype: object

In [107]:
# Importar datos del valor histórico del dólar
dolar = pd.read_csv('../data/staging/dolar_historico_granos.csv', index_col=0)
dolar

,fecha,28/04/2025,29/04/2025,30/04/2025,05/05/2025,06/05/2025,07/05/2025,08/05/2025,09/05/2025,12/05/2025,...,22/05/2025,23/05/2025,26/05/2025,27/05/2025,28/05/2025,29/05/2025,30/05/2025,02/06/2025,03/06/2025,04/06/2025
0,Dólar Oficial,1192.84,1194.45,1194.45,1216.47,1220.45,1152.76,1138.07,1166.96,1148.33,...,1161.91,1157.43,1163.94,1174.39,1176.88,1199.79,1209.35,1199.85,1203.75,1199.07

In [108]:
dolar = dolar.melt()
dolar.head(3)

     variable          value
0       fecha  Dólar Oficial
1  28/04/2025        1192.84
2  29/04/2025        1194.45

In [109]:
dolar = dolar.rename(columns={'variable':'fecha', 'value':'dolar'}).drop(index=0)
dolar.head(3)

        fecha    dolar
1  28/04/2025  1192.84
2  29/04/2025  1194.45
3  30/04/2025  1194.45

In [110]:
print(dolar.loc[10, 'fecha'], '\n')

dolar.loc[10, 'fecha'] = '12/05/2025'

print(dolar.loc[10, 'fecha'])

12/05/2025.1

12/05/2025

In [111]:
dolar['fecha'] = dolar['fecha'].apply(lambda x: x.replace('/', '-'))
dolar['fecha'].head(2)

1    28-04-2025
2    29-04-2025
Name: fecha, dtype: object

In [112]:
dolar['fecha'] = dolar['fecha'].apply(lambda x: '-'.join(x.split('-')[::-1]))
dolar['fecha']

1     2025-04-28
2     2025-04-29
3     2025-04-30
4     2025-05-05
5     2025-05-06
6     2025-05-07
7     2025-05-08
8     2025-05-09
9     2025-05-12
10    2025-05-12
11    2025-05-13
12    2025-05-14
13    2025-05-15
14    2025-05-16
15    2025-05-19
16    2025-05-20
17    2025-05-21
18    2025-05-22
19    2025-05-23
20    2025-05-26
21    2025-05-27
22    2025-05-28
23    2025-05-29
24    2025-05-30
25    2025-06-02
26    2025-06-03
27    2025-06-04
Name: fecha, dtype: object

In [113]:
dolar['fecha'] = pd.to_datetime(dolar['fecha'])
fechas_originales = dolar.index

In [114]:
# Asegurate de que la columna fecha sea datetime y válida
dolar['fecha'] = pd.to_datetime(dolar['fecha'], errors='coerce')

# Eliminá filas con fecha nula o mal parseada
dolar = dolar.dropna(subset=['fecha'])

# Ordená por fecha y eliminá duplicados
dolar = dolar.sort_values('fecha').drop_duplicates('fecha', keep='last')

# Seteá como índice
dolar = dolar.set_index('fecha')

# Reindex diario con ffill o bfill
df_full = dolar.asfreq('D').ffill()

# Volvé a nombrar el índice por prolijidad
df_full.index.name = 'fecha'
df_full = df_full.reset_index()

print(df_full.head(10))

       fecha    dolar
0 2025-04-28  1192.84
1 2025-04-29  1194.45
2 2025-04-30  1194.45
3 2025-05-01  1194.45
4 2025-05-02  1194.45
5 2025-05-03  1194.45
6 2025-05-04  1194.45
7 2025-05-05  1216.47
8 2025-05-06  1220.45
9 2025-05-07  1152.76

/var/folders/4r/91txlfcx43g86h5_v2czs54h0000gn/T/ipykernel_17361/504510342.py:14: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_full = dolar.asfreq('D').ffill()

In [115]:
dolar = df_full

In [116]:
dolar = dolar.reset_index().drop(columns='index')
dolar

        fecha    dolar
0  2025-04-28  1192.84
1  2025-04-29  1194.45
2  2025-04-30  1194.45
3  2025-05-01  1194.45
4  2025-05-02  1194.45
5  2025-05-03  1194.45
6  2025-05-04  1194.45
7  2025-05-05  1216.47
8  2025-05-06  1220.45
9  2025-05-07  1152.76
10 2025-05-08  1138.07
11 2025-05-09  1166.96
12 2025-05-10  1166.96
13 2025-05-11  1166.96
14 2025-05-12  1155.53
15 2025-05-13  1150.30
16 2025-05-14  1153.47
17 2025-05-15  1155.20
18 2025-05-16  1167.84
19 2025-05-17  1167.84
20 2025-05-18  1167.84
21 2025-05-19  1157.77
22 2025-05-20  1162.22
23 2025-05-21  1166.64
24 2025-05-22  1161.91
25 2025-05-23  1157.43
26 2025-05-24  1157.43
27 2025-05-25  1157.43
28 2025-05-26  1163.94
29 2025-05-27  1174.39
30 2025-05-28  1176.88
31 2025-05-29  1199.79
32 2025-05-30  1209.35
33 2025-05-31  1209.35
34 2025-06-01  1209.35
35 2025-06-02  1199.85
36 2025-06-03  1203.75
37 2025-06-04  1199.07

In [117]:
df['fechaOperacion'].iloc[98:102]

98     2025-05-02T14:05:10.593
99     2025-05-02T14:03:41.533
100        2025-05-02T14:02:08
101    2025-05-02T14:00:37.063
Name: fechaOperacion, dtype: object

In [118]:
df['fechaOperacion'] = df['fechaOperacion'].apply(lambda x: x.split('T')[0])
df['fechaOperacion']

0        2025-05-03
1        2025-05-03
2        2025-05-03
3        2025-05-03
4        2025-05-02
            ...
11005    2025-06-01
11006    2025-06-01
11007    2025-06-01
11008    2025-06-01
11009    2025-06-01
Name: fechaOperacion, Length: 11010, dtype: object

In [119]:
df['fechaOperacion'] = pd.to_datetime(df['fechaOperacion'])

In [120]:
print(dolar.columns.tolist())

['fecha', 'dolar']

In [121]:
dolar

        fecha    dolar
0  2025-04-28  1192.84
1  2025-04-29  1194.45
2  2025-04-30  1194.45
3  2025-05-01  1194.45
4  2025-05-02  1194.45
5  2025-05-03  1194.45
6  2025-05-04  1194.45
7  2025-05-05  1216.47
8  2025-05-06  1220.45
9  2025-05-07  1152.76
10 2025-05-08  1138.07
11 2025-05-09  1166.96
12 2025-05-10  1166.96
13 2025-05-11  1166.96
14 2025-05-12  1155.53
15 2025-05-13  1150.30
16 2025-05-14  1153.47
17 2025-05-15  1155.20
18 2025-05-16  1167.84
19 2025-05-17  1167.84
20 2025-05-18  1167.84
21 2025-05-19  1157.77
22 2025-05-20  1162.22
23 2025-05-21  1166.64
24 2025-05-22  1161.91
25 2025-05-23  1157.43
26 2025-05-24  1157.43
27 2025-05-25  1157.43
28 2025-05-26  1163.94
29 2025-05-27  1174.39
30 2025-05-28  1176.88
31 2025-05-29  1199.79
32 2025-05-30  1209.35
33 2025-05-31  1209.35
34 2025-06-01  1209.35
35 2025-06-02  1199.85
36 2025-06-03  1203.75
37 2025-06-04  1199.07

In [122]:
# --- dólar: usar columna 'fecha' y asegurar tipos ---
d = dolar.copy()
d['fecha'] = pd.to_datetime(d['fecha'], dayfirst=True).dt.normalize()
d['dolar'] = pd.to_numeric(d['dolar'], errors='coerce')
d = (d.sort_values('fecha')
       .drop_duplicates('fecha', keep='last'))

# Serie para mapear (clave = fecha, valor = dolar)
s_dolar = d.set_index('fecha')['dolar']

# --- df de operaciones: normalizar fecha ---
df['fechaOperacion'] = pd.to_datetime(df['fechaOperacion'], dayfirst=True).dt.normalize()
df['simboloPrecioPorTN'] = df['simboloPrecioPorTN'].astype(str).str.strip()

# Traer cotización (match por columna, no índice)
df['dolar_en_fecha'] = df['fechaOperacion'].map(s_dolar)

# Calcular precio final (solo divide si símbolo == '$' y hay dólar)
df['precioFijadoFinal'] = np.where(
    (df['simboloPrecioPorTN'] == '$') & df['dolar_en_fecha'].notna(),
    df['precioTN'] / df['dolar_en_fecha'],
    df['precioTN']
)

In [123]:
df

,fechaOperacion,fechaConcertacion,tipoOperacion,tipoModalidad,tipoOiv,grano,volumenTN,condicionCalidad,condicionCalidadAuxiliar,procedenciaProvincia,...,condicionPago,esDestinoFinal,cosecha,numeroOperacionInstancia,nroOperacion,esUltimaInstancia,tipoOiv_v2,operacion_id,dolar_en_fecha,precioFijadoFinal
0,2025-05-03,2025-05-03T00:00:00,Contrato,Compraventa,Fijar Precio/Mercado Comprador,MAIZ,1000.00,Cámara,NaN,CÓRDOBA,...,A plazo,SI,COSECHA 24/25,1,1935460251,Si,Precio a Fijar,1935460251_1,1194.45,NaN
1,2025-05-03,2025-05-03T00:00:00,Contrato,Compraventa,Precio Hecho,TRIGO PAN,283.31,Art. 12,NaN,BUENOS AIRES,...,A plazo,SI,COSECHA 24/25,1,1935140257,Si,Precio Hecho,1935140257_1,1194.45,192.088409
2,2025-05-03,2025-04-30T00:00:00,Contrato,Compraventa,Precio Hecho,SOJA,338.14,Fábrica,NaN,CÓRDOBA,...,A plazo,SI,COSECHA 24/25,1,1935100255,Si,Precio Hecho,1935100255_1,1194.45,249.054460
3,2025-05-03,2025-04-30T00:00:00,Contrato,Compraventa,Precio Hecho,SOJA,295.99,Fábrica,NaN,CÓRDOBA,...,A plazo,SI,COSECHA 24/25,1,1935080254,Si,Precio Hecho,1935080254_1,1194.45,249.054460
4,2025-05-02,2025-05-02T00:00:00,Contrato,Compraventa,Fijar Precio/Mercado Comprador,MAIZ,540.00,Cámara,NaN,CÓRDOBA,...,A plazo,SI,COSECHA 24/25,1,1935060253,Si,Precio a Fijar,1935060253_1,1194.45,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11005,2025-06-01,2025-05-30T00:00:00,Contrato,Compraventa,Precio Hecho,TRIGO PAN,60.00,Cámara,NaN,BUENOS AIRES,...,A plazo,NO,COSECHA 24/25,1,2661180253,No,Precio Hecho,2661180253_1,1209.35,194.319262
11006,2025-06-01,2025-06-01T00:00:00,Contrato,Compraventa,Precio Hecho,SOJA,90.00,Fábrica,NaN,BUENOS AIRES,...,A plazo,NO,COSECHA 24/25,1,2661150257,Si,Precio Hecho,2661150257_1,1209.35,252.201596
11007,2025-06-01,2025-06-01T00:00:00,Contrato,Compraventa,Fijar Precio/Otros,SOJA,300.00,Cámara,NaN,CHACO,...,A plazo,SI,COSECHA 24/25,1,2661130256,Si,Precio a Fijar,2661130256_1,1209.35,NaN
11008,2025-06-01,2025-06-01T00:00:00,Contrato,Compraventa,Fijar Precio/Otros,SOJA,600.00,Cámara,NaN,CHACO,...,A plazo,SI,COSECHA 24/25,1,2661120250,Si,Precio a Fijar,2661120250_1,1209.35,NaN
11009,2025-06-01,2025-06-01T00:00:00,Contrato,Compraventa,Fijar Precio/Otros,SOJA,60.00,Cámara,NaN,SANTA FE,...,A plazo,SI,COSECHA 24/25,1,2661110255,Si,Precio a Fijar,2661110255_1,1209.35,NaN

In [124]:
crocante = df['simboloPrecioPorTN'].value_counts(dropna=False).index[0]
crocante

'$'

In [125]:
df[df['simboloPrecioPorTN']==crocante][['nroOperacion', 'fechaOperacion', 'simboloPrecioPorTN', 'precioTN', 'dolar_en_fecha', 'precioFijadoFinal']]

,nroOperacion,fechaOperacion,simboloPrecioPorTN,precioTN,dolar_en_fecha,precioFijadoFinal
1,1935140257,2025-05-03,$,229440.0,1194.45,192.088409
2,1935100255,2025-05-03,$,297483.1,1194.45,249.054460
3,1935080254,2025-05-03,$,297483.1,1194.45,249.054460
13,1932750259,2025-05-02,$,236000.0,1194.45,197.580476
14,1932380257,2025-05-02,$,302000.0,1194.45,252.836033
...,...,...,...,...,...,...
10996,2661420254,2025-06-02,$,220000.0,1199.85,183.356253
10997,2661410259,2025-06-02,$,241000.0,1199.85,200.858441
10998,2642290250,2025-06-02,$,276000.0,1199.85,230.028754
11005,2661180253,2025-06-01,$,235000.0,1209.35,194.319262
11006,2661150257,2025-06-01,$,305000.0,1209.35,252.201596

In [126]:
df['simboloPrecioPorTN'].value_counts(dropna=False)

simboloPrecioPorTN
$      7361
nan    2295
U$S    1354
Name: count, dtype: int64

In [127]:
df['precioFijadoFinal'] = df['precioFijadoFinal'].apply(lambda x: round(x, 2) if pd.notnull(x) else x)
df['precioFijadoFinal']

0           NaN
1        192.09
2        249.05
3        249.05
4           NaN
          ...
11005    194.32
11006    252.20
11007       NaN
11008       NaN
11009       NaN
Name: precioFijadoFinal, Length: 11010, dtype: float64

In [128]:
df = df.rename(columns={'precioFijadoFinal':'precioHechoUSD'})
df.columns

Index(['fechaOperacion', 'fechaConcertacion', 'tipoOperacion', 'tipoModalidad',
       'tipoOiv', 'grano', 'volumenTN', 'condicionCalidad',
       'condicionCalidadAuxiliar', 'procedenciaProvincia',
       'procedenciaLocalidad', 'simboloPrecioPorTN', 'precioTN',
       'lugarEntrega', 'fechaEntregaDesde', 'fechaEntregaHasta',
       'condicionPago', 'esDestinoFinal', 'cosecha',
       'numeroOperacionInstancia', 'nroOperacion', 'esUltimaInstancia',
       'tipoOiv_v2', 'operacion_id', 'dolar_en_fecha', 'precioHechoUSD'],
      dtype='object')

In [129]:
granos_faltantes_simbolo = df['simboloPrecioPorTN'].value_counts(dropna=False).index[1]
granos_faltantes_simbolo

'nan'

In [136]:
granos_faltantes = df[df['simboloPrecioPorTN']==granos_faltantes_simbolo][['operacion_id', 'nroOperacion', 'volumenTN', 'fechaOperacion', 'simboloPrecioPorTN', 'precioTN', 'dolar_en_fecha', 'precioHechoUSD']]
granos_faltantes

,operacion_id,nroOperacion,volumenTN,fechaOperacion,simboloPrecioPorTN,precioTN,dolar_en_fecha,precioHechoUSD
0,1935460251_1,1935460251,1000.0,2025-05-03,nan,NaN,1194.45,NaN
4,1935060253_1,1935060253,540.0,2025-05-02,nan,NaN,1194.45,NaN
5,1935040252_1,1935040252,1000.0,2025-05-02,nan,NaN,1194.45,NaN
6,1935030257_1,1935030257,1000.0,2025-05-02,nan,NaN,1194.45,NaN
7,1935020251_1,1935020251,360.0,2025-05-02,nan,NaN,1194.45,NaN
...,...,...,...,...,...,...,...,...
11003,2661230250_1,2661230250,60.0,2025-06-01,nan,NaN,1209.35,NaN
11004,2661220255_1,2661220255,30.0,2025-06-01,nan,NaN,1209.35,NaN
11007,2661130256_1,2661130256,300.0,2025-06-01,nan,NaN,1209.35,NaN
11008,2661120250_1,2661120250,600.0,2025-06-01,nan,NaN,1209.35,NaN
11009,2661110255_1,2661110255,60.0,2025-06-01,nan,NaN,1209.35,NaN

In [139]:
nro_op_faltantes = np.unique(np.sort(granos_faltantes['operacion_id'].values))
nro_op_faltantes

array(['1039070258_2', '1066390256_2', '1150300254_2', ..., '851400257_3',
       '861550249_14', '979930259_2'], dtype=object)

In [140]:
len(nro_op_faltantes)

2295